### ISSUE TITLE
documentation build fails

### ISSUE THREAD

**Issue by wuch-g2v** [python-jsonschema/sphinx-json-schema-spec#20]
Looks like something is wring and documentation build fails
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 454, in load_extension
    metadata = setup(app)
  File "/home/builder/rpmbuild/BUILD/sphinx-json-schema-spec-2023.08.1/sphinx_json_schema_spec/__init__.py", line 43, in setup
    documents = {
  File "/home/builder/rpmbuild/BUILD/sphinx-json-schema-spec-2023.08.1/sphinx_json_schema_spec/__init__.py", line 44, in <dictcomp>
    url: fetch_or_load(cache_path=CACHE / f"{name}.html", url=url)
  File "/home/builder/rpmbuild/BUILD/sphinx-json-schema-spec-2023.08.1/sphinx_json_schema_spec/__init__.py", line 81, in fetch_or_load
    response = urllib.request.urlopen(request, context=context)
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

Exception occurred:
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
The full traceback has been saved in /tmp/sphinx-err-0qw7hy31.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by Julian** [comment]
Passes here both locally and [in CI](https://github.com/python-jsonschema/sphinx-json-schema-spec/actions/runs/7155335795/job/19483843919). You'll have to be more specific.
